package com.hbs.edutel.model;

import java.io.Serializable;

public class AutoGeneratedId implements Serializable
{

	private static final long	serialVersionUID	= 1L;

	private String				idFormat;
	private String				idKey;
	private String				idValue;

	public AutoGeneratedId()
	{
		super();
	}

	public AutoGeneratedId(String idKey, String idFormat, String idValue)
	{
		super();
		this.idKey = idKey;
		this.idFormat = idFormat;
		this.idValue = idValue;
	}

	public String getIdFormat()
	{
		return idFormat;
	}

	public String getIdKey()
	{
		return idKey;
	}

	public String getIdValue()
	{
		return idValue;
	}

	public void setIdFormat(String idFormat)
	{
		this.idFormat = idFormat;
	}

	public void setIdKey(String idKey)
	{
		this.idKey = idKey;
	}

	public void setIdValue(String idValue)
	{
		this.idValue = idValue;
	}

}
